name: leaflow 登录签到

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0,12 * * *"

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Gost
        run: |
          curl -L https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz | gunzip > gost
          chmod +x gost

      - name: Install Deps
        run: |
          pip install playwright requests pynacl requests[socks] cryptography
          playwright install chromium --with-deps

      - name: Run Task
        env:
          CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}
          LEAFLOW_LOCALS: ${{ secrets.LEAFLOW_LOCALS }}
          
          # 如果你有通知需求，可以加上 TG 变量
        run: |
          python -u leaflow/leaflow_check.py

      - name: Upload Screenshot on Failure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
